# Generated by Django 2.1.7 on 2019-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('item', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=120)),
                ('specification', models.CharField(max_length=120)),
                ('purchange_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
