# Generated by Django 2.1.7 on 2019-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='Model_No',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
