# Generated by Django 2.1.7 on 2019-07-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190704_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='purchange_price',
            new_name='purchage_price',
        ),
    ]
