# Generated by Django 2.1.7 on 2019-07-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190704_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='purchage_price',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='specification',
            new_name='specificationp',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='type',
            new_name='typep',
        ),
    ]
