# Generated by Django 2.2.3 on 2019-07-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=120)),
                ('Quantity', models.IntegerField(default='0')),
            ],
        ),
    ]
