# Generated by Django 2.2.3 on 2019-07-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_demand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demand',
            new_name='DemandModel',
        ),
    ]
