# Generated by Django 2.2.3 on 2019-07-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190718_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(default='0')),
            ],
        ),
        migrations.DeleteModel(
            name='DemandModel',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='Notice',
            new_name='notice',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='specificationp',
            new_name='item_specification',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='typep',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='Model_No',
            new_name='model_no',
        ),
    ]
