# Generated by Django 2.2.3 on 2019-07-23 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190723_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
