# Generated by Django 2.2.3 on 2019-09-12 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_demand_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_specification',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
